#!/bin/bash
usage() { echo "Usage: $0 [-p <string>]" 1>&2; exit 1; }
logo() {
cat<<EOF
  ___ _  _ ___     ___ ___ ___ _   _ ___ ___ 
 | _ \ || | _ \___/ __| __/ __| | | | _ \ __|
 |  _/ __ |  _/___\__ \ _| (__| |_| |   / _| 
 |_| |_||_|_|     |___/___\___|\___/|_|_\___|

Conribute on: https://github.com/prathik/php-secure
Credits: Prathik Rajendran M (@prathikraj)                                             
EOF
}
while getopts "f:s" o; do
    case "${o}" in
        f)
            f=${OPTARG}
            ;;
	s)
	    s=true
	    ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${f}" ]; then
    usage
fi

logo
echo -e "\nRuning on folder ${f}";

functions=`sqlite3 php-secure.db "select * from injection_functions" | tr "\\n" "|"`
pat=${functions%?}

echo -e "\nCritical\n"
find $f -name "*.php" | xargs grep -E "($pat)[^;]*;" -o | grep -E "\\\$_(GET|POST)"

echo -e "\nConsider adding htmlentities to the following variables\n"
find $f -name "*.php" | xargs grep -Eo "\\\$\w+[ ]*=[^;]+;" | grep -E "\\\$_(GET|POST)" | grep -v "(htmlentities|esc_attr)"

if [ -z "${s}" ] ; then
    echo -e "\nAll\n"
    find $f -name "*.php" | xargs grep -E "($pat)[^;]*;" -o | grep -E "\\$\w+"
    find $f -name "*.php" | xargs grep -Eo "\\\$\w+[ ]*=[^;]+;" | grep -E "\\\$_(GET|POST)" | grep -v "(htmlentities|esc_attr)"
fi
