#!/bin/bash
usage() { echo "Usage: $0 [-p <string>]" 1>&2; exit 1; }
logo() {
cat<<EOF
  ___ _  _ ___     ___ ___ ___ _   _ ___ ___ 
 | _ \ || | _ \___/ __| __/ __| | | | _ \ __|
 |  _/ __ |  _/___\__ \ _| (__| |_| |   / _| 
 |_| |_||_|_|     |___/___\___|\___/|_|_\___|

Conribute on: https://github.com/prathik/php-secure
Credits: Prathik Rajendran M (@prathikraj)                                             
EOF
}
while getopts ":f:" o; do
    case "${o}" in
        f)
            f=${OPTARG}
            ;;
        *)
            usage
            ;;
    esac
done
shift $((OPTIND-1))

if [ -z "${f}" ]; then
    usage
fi

logo
echo -e "\nRuning on folder ${f}\n";

functions=('require','include','include_once','require_once','unlink')
pat=$(echo ${functions[@]}|tr "," "|")

find $f -name "*.php" | xargs grep -E "($pat)\([^$]*\\\$[^)]*\)[ ^;]*;" -o
